name = "DocstringTranslationGoogleTransBackend"
uuid = "efedaf41-d47e-40e2-8e7a-242c6575e753"
authors = ["Satoshi Terasaki <terasakisatoshi.math@gmail.com>"]
version = "0.1.0"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
CondaPkg = "0.2.24"
Markdown = "1.11.0"
PythonCall = "0.9.23"
